#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huangzi #?useUnicode=yes&amp;characterEncoding=UTF-8
    username: root
    password: xgllhz

